{% set version = "1.6.3" %}

package:
  name: keyutils
  version: {{ version }}

source:
  url: https://git.kernel.org/pub/scm/linux/kernel/git/dhowells/keyutils.git/snapshot/keyutils-{{ version }}.tar.gz
  sha256: a61d5706136ae4c05bd48f86186bcfdbd88dd8bd5107e3e195c924cfc1b39bb4
  patches:
    - patches/0001-Make-endian-detection-in-work-on-non-RHEL-distributi.patch
    - patches/0002-Fix-installing-shared-library-symlinks-with-DESTDIR.patch

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    # https://abi-laboratory.pro/tracker/timeline/keyutils/
    - {{ pin_subpackage('keyutils', max_pin='x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    # build wants to use g++ symlink
    - gxx
    - make
    - file

test:
  commands:
    - test -f ${PREFIX}/lib/libkeyutils.so
    - keyctl --version | grep '{{ version }}'
    # These tests can't work inside docker without additional security flags
    # - keyctl add user cf-keyctl-key cf-keyctl-value @s
    # - keyctl print $(keyctl search @s user cf-keyctl-key) | grep cf-keyctl-value
    # - keyctl unlink $(keyctl search @s user cf-keyctl-key) @s

about:
  home: https://git.kernel.org/pub/scm/linux/kernel/git/dhowells/keyutils.git/
  license: LGPL-2.1-or-later
  license_file: LICENCE.LGPL
  summary: Linux Key Management Utilities
  description: |
    Keyutils is a set of utilities for managing the key retention facility in
    the kernel, which can be used by filesystems, block devices and more to
    gain and retain the authorization and encryption keys required to perform
    secure operations.

extra:
  recipe-maintainers:
    - chrisburr
